name: Bug Report
description: Report a problem in NotchSpace
labels: [bug]

body:

* type: textarea
  attributes:
  label: "Problem"
  description: "Describe the current behavior. This may include crash logs, images, or videos."
  validations:
  required: true

* type: textarea
  attributes:
  label: "Steps to reproduce"
  description: "List the steps to reproduce the problem."
  placeholder: |
  Open NotchSpace
  Click ...
  Issue occurs
  validations:
  required: true

* type: textarea
  attributes:
  label: "Expected behavior"
  description: "Describe the behavior you expect."
  validations:
  required: true

* type: input
  attributes:
  label: "Menu bar/display affecting apps"
  description: "Apps like Bartender, Ice, BetterDisplay, etc."
  placeholder: "Bartender"
  validations:
  required: false

* type: input
  attributes:
  label: "NotchSpace version"
  description: |
  1. Open NotchSpace
  2. Go to Settings
  3. Click "About"
  placeholder: "1.0.0 (12)"
  validations:
  required: true

* type: input
  attributes:
  label: "Mac/MacBook model"
  placeholder: "MacBook Air M2"
  validations:
  required: true

* type: input
  attributes:
  label: "macOS version"
  placeholder: "macOS 14.5"
  validations:
  required: true

* type: checkboxes
  attributes:
  label: "macOS Beta"
  description: "Are you currently using a macOS beta?"
  options:
  - label: "Yes"
  required: false

* type: checkboxes
  attributes:
  label: "Agreements"
  description: "Check the following before submitting."
  options:
  - label: "My title is clear and specific."
  required: true
  - label: "I am using the latest version."
  required: true
  - label: "I searched existing issues."
  required: true
  - label: "This is not a usage or how-to question."
  required: true
  - label: "This is not a license or refund issue."
  required: true
